<?php /** @var \BodenkoVV\AskQuestion\Block\Questions $block */
$questions = $block->getQuestions(10);
?>
<ol>
    <?php /** @var \BodenkoVV\AskQuestion\Model\Question $question */
    foreach ($questions as $question):
        ?>
        <li>
            <p><?= __('From \"<b>%1</b>\": [%2]', $question->getName(), $question->getQuestion()) ?><b> to product:</b> <?= $question->getProductName()?></p>
        </li>
    <?php endforeach; ?>
</ol>

