<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

    <div class="block">
        <h1>baner</h1>
        <div >
            <a href="https://www.pexels.com/search/background/"><img src="https://images.pexels.com/photos/207171/pexels-photo-207171.jpeg" width="189" height="255" alt="lorem">click me!!!</a>
        </div>
    </div>

