<div class="content-wrapper">
    <?php if ($block->getHomeworkText()):?>
        <h1>
            <span><?= $block->escapeHtml(__('Your request was successfully'))?></span>
        </h1>
        <h2>
            <?= $block->escapeHtml(__($block->getHomeworkText())) ?>
        </h2>
    <?php endif;
    $myJsonController='home-work/jsonresponse';
    ?>
	<a href="<?= $block->getUrl($myJsonController) ?>"> Link JSON </a>
</div>
