<div class="content-wrapper">

    <?php if ($block->getHomeworkText()):?>
        <h1>
            <span>Your request was successfully</span>
        </h1>
        <h2>
            <?= /* @escapeNotVerified */ $block->getHomeworkText(); ?>
        </h2>
    <?php endif;
    $myjsoncontroller='homework/JsonResponse';
    ?>
	<a href="<?= $block->getUrl($myjsoncontroller) ?>"> Link JSON </a>

    <?php if ($block->myurltext($myjsoncontroller)):?>
        <h2>
            <a href="<?= /* @escapeNotVerified */ $block->myurltext($myjsoncontroller); ?>"> from block function get URL json</a>
        </h2>
    <?php endif;?>

</div>
