<div class="content-wrapper">

    <?php if ($block->getHomeworkText()):?>
        <h1>
            <span>Your request was successfully</span>
        </h1>
        <h2>
            <?= /* @escapeNotVerified */ $block->getHomeworkText(); ?>
        </h2>
    <?php endif;
    $myjsoncontroller='home-work/jsonresponse';
    ?>
	<a href="<?= $block->getUrl($myjsoncontroller) ?>"> Link JSON </a>

</div>
