<?php
declare(strict_types=1);
namespace part1_Class;

use FilesystemIterator;
use RecursiveDirectoryIterator;
use RecursiveIteratorIterator;
use RegexIterator;
use RecursiveRegexIterator;

class PathContent
{
    public function getPathContent($path = './app')
    {
        $path = realpath($path);
        $directory = new \RecursiveDirectoryIterator($path);
        $iterator = new \RecursiveIteratorIterator($directory, RecursiveIteratorIterator::CHILD_FIRST);
        foreach ($iterator as $filename) {
            $name = $filename->getFilename();
            if ($filename->isDir()){
                echo "dir :  -  : ";
            }
            else {
                $filesize = $filename->getSize();
                echo "file: ".number_format($filesize)."kB : ";
            }

            $stat = stat($filename->getPathname());
            if (!($stat['mtime']===null)){
                $timeModify = date("Y/m/d H:i:s",$stat['mtime']);
            } else {
                $timeModify = '';
            }

            if (!($stat['atime']===null)){
                $timeLastAccess = date("Y/m/d H:i:s",$stat['atime']);
            } else {
                $timeLastAccess = $timeModify;
            }
                echo "$timeModify : $timeLastAccess : $filename\n";
        }
    }
}

$foo1 = new PathContent();
$foo1->getPathContent('./app/code');
