<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

    <div class="block">
        <h1>test</h1>
        <div>
            <a href="https://www.pexels.com/search/background/"><img src="https://images.pexels.com/photos/207171/pexels-photo-207171.jpeg" width="189" height="255" alt="lorem"><br>test click!!!</a>
        </div>
        <h1><?php echo $this->getWorld2Txt(); ?></h1>
        <br>
        <h1>
            <?php
                $title = $this->getData('title');
                $count = $this->getData('count');
                echo $title.' ---- '.$count;
            ?>
        </h1>

<!--
        <form name="test" method="post" action="input1.php">
            <p><b>Ваше имя:</b><br>
                <input type="text" size="40">
            </p>
            <p><b>Каким браузером в основном пользуетесь:</b><Br>
                <input type="radio" name="browser" value="ie"> Internet Explorer<Br>
                <input type="radio" name="browser" value="opera"> Opera<Br>
                <input type="radio" name="browser" value="firefox"> Firefox<Br>
            </p>
            <p>Комментарий<Br>
                <textarea name="comment" cols="40" rows="3"></textarea></p>
            <p><input type="submit" value="Отправить">
                <input type="reset" value="Очистить"></p>
        </form>
    -->
    </div>

