<div id="header-head-rfd">
    <a href="#" id="link-register" data-mage-init='{"homework5": {}}'><?= $block->escapeHtml(__('__Registration for dealer__'))?></a>
</div>
<!--data-mage-init='{"homework5": {}}'-->
<div id="header-rfd"
     style="display:none;">
    <div id="registration-for-dealer">
    </div>
<!--    <script type="text/x-magento-init">-->
<!--    {-->
<!--        "#link-register": {-->
<!--            "BodenkoVV_Homework5/js/link-register": {-->
<!--                "":""-->
<!--            }-->
<!--        }-->
<!--    }-->
<!--    </script>-->
</div>
