<?php
/**
 * @var  \Magento\Catalog\Block\Product\View
 */
?>
<div>
    <a href="#" id="click-header">Registration for dealer</a>
</div>
<?php

?>

<div id="header-mpdal" style="display:none;">
    <div id="registrationfordealer">
    </div>
</div>
<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function(
            $,
            modal
        ) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: '',
                buttons: [{
                    text: $.mage.__('Close'),
                    class: '',
                    click: function () {
                        $('#registrationfordealer').empty();
                        this.closeModal();
                    }
                }]
            };
            var popup = modal(options, $('#header-mpdal'));
            $("#click-header").on('click',function(){
                var modalContent = '<iframe width="1024" height="760"'+
                    'src="https://magento226.local/customer/account/create/">'+
                    '</iframe>';
                $('#registrationfordealer').html(modalContent);
                $("#header-mpdal").modal("openModal");
            });
        }
    );
</script>