<?php
/**
 * @var $block BodenkoVV\AskQuestion\Block\TabAskQuestion
 */
?>
<?php if ($block->askQuestionEnable) {
?>
    <div class="homework11-askquestion-block">
        <?php
        echo 'Store ID = ['.$block->helperData->_storeManager->getStore()->getId().']<hr>';


        foreach ($block->getQuestionByProductSku() as $Items):
         ?>
            <h2><?= $block->escapeHtml(__($Items->getQuestion())); ?></h2>
            <sup><b title="<?= $block->escapeHtml(__($Items->getPhone())).' & '.$block->escapeHtml(__($Items->getEmail()));?>"><?= $block->escapeHtml(__($Items->getName())).'</b> - '.$block->escapeHtml(__($Items->getQuestionDate())); ?></sup>
            <hr>
            <h2><?= $block->escapeHtml(__($Items->getAnswer())); ?></h2>
        <?php
        endforeach;
        ?>
    </div>
<?php
}
?>

